# Generated by Django 4.2.7 on 2024-02-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpComingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_images/upcoming/')),
            ],
        ),
    ]
