# Generated by Django 4.2.7 on 2024-02-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Lists', '0002_upcomingproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='Product_Lists.category'),
        ),
    ]
